backend:
  name: git-gateway
  branch: master

media_folder: src/assets/images/uploads
public_folder: assets/images/uploads

collections:
  - label: "Poets"
    name: "poet"
    folder: "src/content/poets"
    create: true
    identifier_field: id
    format: json
    extension: json
    filter: {field: "language", value: "en"}
    fields:
     - {label: "ID", name: id, widget: "string"}
     - label: "English language"
       name: "en"
       widget: "object"
       fields:
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Location", name: "location", widget: "string"}
        - {label: "Years of life", name: "yearsOfLife", widget: "string"}
        - {label: "Bio", name: "bio", widget: "markdown"}
        - label: "Timeline"
          name: "timeline"
          widget: "list"
          fields:
            - label: "Time"
              name: "time"
              widget: "string"
              default: "1980"
            - label: "Description"
              name: "description"
              widget: "string"
        - label: "Poems"
          name: "poems"
          widget: "list"
          fields:
            - label: "Year of poem"
              name: "poemYear"
              widget: "string"
              default: "1980"
            - label: "Poem"
              name: "poem"
              widget: "string"
        - label: "Video"
          name: "video"
          widget: "string"
     - label: "Русский язык"
       name: "ru"
       widget: "object"
       fields:
        - {label: "Имя", name: "name", widget: "string"}
        - {label: "Годы жизни", name: "yearsOfLife", widget: "string"}
        - {label: "Место", name: "location", widget: "string"}
        - {label: "Биография", name: "bio", widget: "markdown"}
        - label: "Хронология"
          name: "timeline"
          widget: "list"
          fields:
            - label: "Время"
              name: "time"
              widget: "string"
              default: "1980"
            - label: "Описание"
              name: "description"
              widget: "string"
        - label: "Произведения"
          name: "poems"
          widget: "list"
          fields:
            - label: "Год выхода произведения"
              name: "poemYear"
              widget: "string"
              default: "1980"
            - label: "Название произведения"
              name: "poem"
              widget: "string"
        - label: "Видео"
          name: "video"
          widget: "string"
     - label: "Беларуская мова"
       name: "be"
       widget: "object"
       fields:
        - {label: "Імя", name: "name", widget: "string"}
        - {label: "Гады жыцця", name: "yearsOfLife", widget: "string"}
        - {label: "Месца", name: "location", widget: "string"}
        - {label: "Біяграфія", name: "bio", widget: "markdown"}
        - label: "Храналогія"
          name: "timeline"
          widget: "list"
          fields:
            - label: "Час"
              name: "time"
              widget: "string"
              default: "1980"
            - label: "Апісанне"
              name: "description"
              widget: "string"
        - label: "Творы"
          name: "poems"
          widget: "list"
          fields:
            - label: "Год выхаду твора"
              name: "poemYear"
              widget: "string"
              default: "1980"
            - label: "Назва твора"
              name: "poem"
              widget: "string"
        - label: "Відэа"
          name: "video"
          widget: "string"
     - label: "Gallery/Галерея/Галерэя"
       name: "galleryImages"
       widget: "list"
       fields:
        - label: "Image/Изображение/Малюнак"
          name: "image"
          widget: image