backend:
  name: git-gateway
  repo: vldmr1/Culture-Portal
  branch: cms

media_folder: src/assets/images/uploads
public_folder: assets/images/uploads
# publish_mode: editorial_workflow

collections:
  - label: "Poets"
    name: "poet"
    folder: "src/content/poets"
    create: true
    identifier_field: id
    format: json
    extension: json
    filter: {field: "language", value: "en"}
    fields:
     - {label: "ID", name: id, widget: "string"}
     - {label: "Years of life / Годы жизни / Гады Жыцця", name: "yearsOfLife", widget: "string"}
     - {label: "Photo / Фото / фота", name: "photo", widget: "image"}
     - {label: "Video / Видео / Вiдэа", name: "video", widget: "string"}
     - {label: "Map id", name: "mapId", widget: "string"}
     - label: "Русский язык"
       name: "ru"
       widget: "object"
       fields:
        - {label: "Имя", name: "name", widget: "string"}
        - {label: "Место", name: "location", widget: "string"}
        - {label: "Биография", name: "desc", widget: "markdown"}
        - label: "Хронология"
          name: "timeline"
          widget: "list"
          fields:
            - { label: "Время", name: "time", widget: "string", default: "1980" }
            - { label: "Заголовок", name: "title", widget: "string" }
            - { label: "Описание", name: "description", widget: "string" }
        - label: "Произведения"
          name: "poems"
          widget: "list"
          fields:
            - label: "Group name"
              name: "group"
              widget: "string"
            - label: "Works"
              name: "works"
              widget: "list"
              fields:
                - label: "Название произведения"
                  name: "name"
                  widget: "string"
                - label: "Год выхода произведения"
                  name: "date"
                  widget: "string"
     - label: "Беларуская мова"
       name: "be"
       widget: "object"
       fields:
        - {label: "Імя", name: "name", widget: "string"}
        - {label: "Месца", name: "location", widget: "string"}
        - {label: "Біяграфія", name: "desc", widget: "markdown"}
        - label: "Храналогія"
          name: "timeline"
          widget: "list"
          fields:
            - { label: "Час", name: "time", widget: "string", default: "1980" }
            - { label: "Загаловак", name: "title", widget: "string" }
            - { label: "Апісанне", name: "description", widget: "string" }
        - label: "Творы"
          name: "poems"
          widget: "list"
          fields:
            - label: "Group name"
              name: "group"
              widget: "string"
            - label: "Works"
              name: "works"
              widget: "list"
              fields:
                - label: "Назва твора"
                  name: "name"
                  widget: "string"
                - label: "Год выхаду твора"
                  name: "date"
                  widget: "string"
     - label: "English language"
       name: "en"
       widget: "object"
       fields:
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Location", name: "location", widget: "string"}
        - {label: "Bio", name: "desc", widget: "markdown"}
        - label: "Timeline"
          name: "timeline"
          widget: "list"
          fields:
            - { label: "Time", name: "time", widget: "string", default: "1980" }
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Description", name: "description", widget: "string" }
        - label: "Poems"
          name: "poems"
          widget: "list"
          fields:
            - label: "Group name"
              name: "group"
              widget: "string"
            - label: "Works"
              name: "works"
              widget: "list"
              fields:
                - label: "Name"
                  name: "name"
                  widget: "string"
                - label: "Date"
                  name: "date"
                  widget: "string"
     - label: "Gallery/Галерея/Галерэя"
       name: "galleryImages"
       widget: "list"
       fields:
        - label: "Image/Изображение/Малюнак"
          name: "image"
          widget: image
